services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/chatdb?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000
      - FRONTEND_URL=http://localhost:5173
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

volumes:
  db_data: